/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeFilter_ChannelBalancer */

#ifndef _Included_NativeFilter_ChannelBalancer
#define _Included_NativeFilter_ChannelBalancer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeFilter_ChannelBalancer
 * Method:    processData
 * Signature: ([DIIDDD)V
 */
JNIEXPORT void JNICALL Java_NativeFilter_ChannelBalancer_processData
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
