/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeFilter_Limiter */

#ifndef _Included_NativeFilter_Limiter
#define _Included_NativeFilter_Limiter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeFilter_Limiter
 * Method:    processData
 * Signature: ([DIIDDDDD)V
 */
JNIEXPORT void JNICALL Java_NativeFilter_Limiter_processData
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
