/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeFilter_GraphicEqualizer */

#ifndef _Included_NativeFilter_GraphicEqualizer
#define _Included_NativeFilter_GraphicEqualizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeFilter_GraphicEqualizer
 * Method:    processData
 * Signature: ([DIIF[DD)V
 */
JNIEXPORT void JNICALL Java_NativeFilter_GraphicEqualizer_processData
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jfloat, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
